### ISSUE TITLE
Replace use of Field with Annotated

### ISSUE THREAD

**Issue by DiamondJoseph** [bluesky/scanspec#160]
Now that the related Pydantic issue has been closed, we can follow through on this TODO and replace Field default arguments with annotated typehints for the dataclasses contained within.

**Comment by coretl** [comment]
After a brief look I can't see the bit of pydantic docs that says you can put description in as a bare string, where did you find that bit of information?

**Comment by callumforrester** [comment]
I suspect I just wanted to put it back how it was when we used vanilla dataclasses, before we adopted pydantic. The issue was resolved for v1 but may not have been for v2 (https://github.com/pydantic/pydantic/issues/3496#issuecomment-1597473757).

**Comment by DiamondJoseph** [comment]
The PR that closed that issue was 9 days after the comment saying it was still an issue in Pydantic v2: I believe it is resolved for v2.

**Comment by coretl** [comment]
I see no reference in that PR of using bare strings in annotations...

**Comment by DiamondJoseph** [comment]
[See above](https://github.com/bluesky/scanspec/issues/160#issuecomment-2656123616), think I jumped the gun and we need at least as much as `field: Annotated[type, Field(description="")]`
